---
services:
  - docker
  - redis
language: go
go:
  - 1.7.5
  - 1.8

before_install:
  - docker run -d -p 5984:5984 --net=host --name couch klaemo/couchdb:2.0.0

before_script:
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter --deadline 120s --dupl-threshold 70 -D interfacer -D errcheck -D gocyclo -D dupl ./...

script:
  - ./scripts/coverage.sh
  - ./scripts/integration.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - docker ps -a
  - docker logs couch
