---
dist: trusty

services:
  - docker
  - redis

language: go

matrix:
  include:
    - go: "1.11"
      env: COMMAND=scripts/lint.sh
    - go: "1.11"
      env: COMMAND=scripts/unit-test.sh
    - go: "1.10"
      env: COMMAND=scripts/unit-test.sh
    - go: "1.9"
      env: COMMAND=scripts/unit-test.sh
    - go: "1.11"
      env: COMMAND=scripts/sharing-test.sh
    - go: "1.11"
      env: COMMAND=scripts/clone-test.sh

before_install:
  - docker run -d -p 5984:5984 --net=host --name couch apache/couchdb:2.2

before_script:
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}

script:
  - bash $COMMAND

after_failure:
  - docker ps -a
