name: Build docs and shell completions
on:
  push:
    branches:
      - master
    paths:
      - 'cmd/*.go'
jobs:
  build_cli:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Install
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go install
      - name: Build
        run: |
          make cli
      - uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Build CLI docs and shell completions
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
